### ISSUE TITLE
UAVO Generator code? 

### ISSUE THREAD

**Issue by MAVProxyUser** [aughey/uavtalk_json#1]
do you have the code that generated this?

**Comment by aughey** [comment]
Yes. I created a generator in the openpilot source tree. I can make a fork,
push it, and issue a pull request if you want.

**Comment by MAVProxyUser** [comment]
Yes please!

**Comment by aughey** [comment]
I've made a fork of the OpenPilot master at
https://github.com/aughey/OpenPilot, pushed my changes there, and submitted
pull request https://github.com/openpilot/OpenPilot/pull/5

John

**Comment by MAVProxyUser** [comment]
You rock sir. I’ll push it in manually as I can’t control pull requests atm. 

Cheers! 
-KF

**Comment by aughey** [comment]
I've added a few extra changes just now.  An unpack string and a size
field.  This simply reduces complexity on the javascript for generating an
unpacker.

John

**Comment by MAVProxyUser** [comment]
Excellent. I will pull it in tomorrow morning. 
-KF

**Comment by MAVProxyUser** [comment]
I've added my latest updates to your work here: 
https://reviews.openpilot.org/changelog/OpenPilot?cs=52943d1d55d3c42d7d3216e3d44b376569a7ddde
